/**
 ******************************************************************************
 * @file    ad9959.c
 * @brief   AD9959 DDS Driver Implementation
 *
 * 2-wire serial mode:
 *   SDIO0 = SPI1_MOSI (PD7), SDIO1 = SPI3_MOSI (PD6)
 *   SCLK  = SPI1_SCK (PB3) + SPI3_SCK (PC10) synchronous
 *   CS    = SPI1_NSS (PA15) hardware pulse mode
 *
 * Phase 1: both SPI lanes send identical data (redundant dual-wire).
 * Encoder pre-splits data if bit-interleaving is needed later.
 ******************************************************************************
 */

#include "ad9959.h"
#include "ad9959_reg.h"
#include "bsp_spi.h"
#include "bsp_gpio.h"
#include "bsp_tim.h"
#include "drv_74hc595_1.h"
#include "detect_task.h"
#include <string.h>

/* ================================================================
 * Internal: Timeout Wait (debugger-friendly, HAL_GetTick based)
 * ================================================================ */

/**
  * @brief  Block until timeout entry expires.
  * @param  toe: timeout entry index (enum errorlist)
  * @note   Uses Detect_Hook + Detect_Task polling — allows debugger break.
  */
static void AD9959_WaitToe(uint8_t toe)
{
    Detect_Hook(toe);
    while (!is_TOE_Overtime(toe)) {
        Detect_Task();
    }
}

/* ================================================================
 * Internal: Power-Up Sequence (via 595)
 * ================================================================ */

static void AD9959_PowerUpSequence(void)
{
    /* Full DDS power-up via 74HC595:
     *   DRV_595_PowerSeq_Init() handles:
     *     1. OE disabled, all outputs low
     *     2. Enable DDS 1.8V digital (DDSPWREN1V8D)
     *     3. Enable DDS 1.8V analog  (DDSPWREN1V8A)
     *     4. Wait 10ms for rails
     *     5. Enable DDS 3.3V digital (DDSPWREN_3V3D)
     *     6. Set REF_CLK mode = 3.3V (DDSCLKMODE33)
     *     7. Master Reset pulse (DDSMASTERRST)
     *     8. Enable outputs
     */
    DRV_595_PowerSeq_Init();
}

/* ================================================================
 * Internal: PLL Configuration (FR1)
 * REF_CLK = 25.6 MHz (TIM15: ARR=9 → 256/10), SYSCLK = 486.4 MHz
 * PFD = 25.6 MHz, PLL ×19 = 486.4 MHz (max ≤500 MHz per DS)
 * ================================================================ */

void AD9959_ConfigPLL(void)
{
    /* TIM15 REFCLK: ARR=9 → 256 MHz/(9+1) = 25.6 MHz, 50% duty */
    BSP_TIM15_SetREFCLK(25000000UL);
    BSP_TIM15_Start();

    uint8_t fr1_data[3];
    uint32_t fr1_val = 0;

    /* VCO gain = HIGH (SYSCLK 486.4 MHz > 255 MHz)  [23] */
    fr1_val |= FR1_VCO_GAIN_HIGH;
    /* PLL multiplier = 19  [22:18]  (25.6 × 19 = 486.4 MHz) */
    fr1_val |= FR1_PLL_DIV(19);
    /* Charge pump = 75 uA  [17:16]  (DS: best phase noise) */
    fr1_val |= FR1_CP_75uA;

    fr1_data[0] = (fr1_val >> 16) & 0xFF;
    fr1_data[1] = (fr1_val >> 8)  & 0xFF;
    fr1_data[2] =  fr1_val        & 0xFF;

    AD9959_WriteRegister(AD9959_REG_FR1, fr1_data, 3);

    /* IO_UPDATE required to latch FR1 and start PLL.
       Without this, PLL stays disabled → SYSCLK = REFCLK = 25.6 MHz. */
    AD9959_IOUpdate();
}

/* ================================================================
 * Public API
 * ================================================================ */

void AD9959_Init(void)
{
    /* Phase 1: Power rails via 595 + stability wait */
    AD9959_PowerUpSequence();                    /* 595: power rails ON             */
    AD9959_WaitToe(DDS_POWER_STABLE_TOE);        /* 15ms: rail + REFCLK stabilize   */

    /* Phase 2: Hardware Master Reset (via 595 DDSMASTERRST) */
    AD9959_Reset();                              /* MRST pulse, 2ms hold            */
    AD9959_WaitToe(DDS_RESET_RECOVERY_TOE);      /* 5ms: register defaults settle   */

    /* Phase 3: PLL configuration (TIM15 REFCLK + FR1 write) */
    AD9959_ConfigPLL();                          /* REFCLK=25.6MHz, PLL×19=486.4MHz */
    AD9959_WaitToe(DDS_PLL_LOCK_TOE);            /* 1ms: PLL lock                   */

    /* Phase 4: CSR — single-bit 2-wire mode, CH0 only
       (channel enable takes effect immediately, no IO_UPDATE needed.
        IO_UPDATE deferred to Debug_CW_Test / app-level after all channel regs) */
    uint8_t csr = CSR_CH0_ENABLE;
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);
}

void AD9959_IOUpdate(void)
{
    /* Init-phase software IO_UPDATE: briefly reconfigure PC6 as GPIO,
     * pulse high, restore to AF (TIM8_CH1).
     * Runtime IO_UPDATE is generated by TIM8 CH1 hardware pulse. */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = SYNC_9959_IO_UPDATE_Pin;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    HAL_GPIO_Init(SYNC_9959_IO_UPDATE_GPIO_Port, &gpio);

    HAL_GPIO_WritePin(SYNC_9959_IO_UPDATE_GPIO_Port, SYNC_9959_IO_UPDATE_Pin, GPIO_PIN_SET);
    for (volatile int i = 0; i < 100; i++) {}
    HAL_GPIO_WritePin(SYNC_9959_IO_UPDATE_GPIO_Port, SYNC_9959_IO_UPDATE_Pin, GPIO_PIN_RESET);

    /* Restore AF for TIM8_CH1 */
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Alternate = GPIO_AF3_TIM8;
    HAL_GPIO_Init(SYNC_9959_IO_UPDATE_GPIO_Port, &gpio);
}

void AD9959_Reset(void)
{
    /* DDS Master Reset via 595 — AD9959 MASTER_RESET pin is ACTIVE HIGH
       (DS p9: "Active High Reset Pin"). Assert = HIGH, Release = LOW. */
    DRV_595_SetBit(SHIFTREG_DDS_MASTERRST, 1);   /* assert reset (high) */
    AD9959_WaitToe(DDS_RESET_HOLD_TOE);           /* 2ms hold            */
    DRV_595_SetBit(SHIFTREG_DDS_MASTERRST, 0);   /* release reset (low) */
}

void AD9959_PowerDown(bool enable)
{
    /* DDS power-down via 595 (DDSPDN bit) */
    DRV_595_SetBit(SHIFTREG_DDS_PDN, enable ? 1 : 0);
}

/* ================================================================
 * Register Access
 * ================================================================ */

void AD9959_WriteRegister(uint8_t reg, const uint8_t *data, uint8_t num_bytes)
{
    uint8_t frame[32];
    if (num_bytes > 31) return;
    frame[0] = reg & 0x7F;
    memcpy(frame + 1, data, num_bytes);
    uint8_t total = num_bytes + 1;

    /* Blocking SPI transmit — SPI1 only (SDIO_0). SPI3 unused in single-bit mode. */
    BSP_SPI_Transmit(SPI1, frame, total);
}

void AD9959_ReadRegister(uint8_t reg, uint8_t *data, uint8_t num_bytes)
{
    (void)reg;
    memset(data, 0, num_bytes);
}

/* ================================================================
 * High-Level Setters
 * ================================================================ */

void AD9959_SetFTW(uint8_t channel, uint32_t ftw)
{
    /* CSR[7:4] selects target channel before CFTW write */
    uint8_t csr = CSR_CHANNEL(channel);
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    uint8_t buf[4];
    buf[0] = (ftw >> 24) & 0xFF;
    buf[1] = (ftw >> 16) & 0xFF;
    buf[2] = (ftw >> 8)  & 0xFF;
    buf[3] =  ftw        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_CFTW, buf, 4);
}

void AD9959_SetASF(uint8_t channel, uint16_t asf)
{
    /* CSR[7:4] selects channel; ACR has NO internal channel bits */
    uint8_t csr = CSR_CHANNEL(channel);
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    uint8_t buf[3];
    uint32_t acr = ((uint32_t)(asf & ACR_ASF_Msk) << ACR_ASF_Pos) |
                   ACR_AMP_MULT_ENABLE;
    buf[0] = (acr >> 16) & 0xFF;
    buf[1] = (acr >> 8)  & 0xFF;
    buf[2] =  acr        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_ACR, buf, 3);
}

void AD9959_SetPOW(uint8_t channel, uint16_t pow)
{
    uint8_t csr = CSR_CHANNEL(channel);
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    uint8_t buf[2];
    buf[0] = (pow >> 8) & 0xFF;
    buf[1] =  pow       & 0xFF;
    AD9959_WriteRegister(AD9959_REG_CPOW, buf, 2);
}

void AD9959_SetChannelMask(uint8_t channel_mask)
{
    /* channel_mask uses CSR[7:4]. Also set 2-wire mode [2:1]=00, MSB first [0]=0. */
    uint8_t csr = (channel_mask << 4) & CSR_CHANNEL_MASK;
    csr |= CSR_IO_MODE_2BIT;
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);
}

/* ================================================================
 * Debug: Single-Channel CW Test
 * ================================================================ */

/**
  * @brief  Configure CH0 for CW output at given frequency, max amplitude.
  * @param  freq_hz: output frequency in Hz (e.g. 200000000)
  * @note   Call after AD9959_Init(). Blocking SPI, single-wire mode.
  */
void AD9959_Debug_CW_Test(uint32_t freq_hz)
{
    /* 1. CFR: sine output + DAC full current + matched pipe delays (DS: single-tone) */
    uint8_t cfr[3];
    uint32_t cfr_val = CFR_DAC_FULL_CURRENT | CFR_SINE_OUT_ENABLE
                     | CFR_MATCHED_PIPE_DELAYS;
    cfr[0] = (cfr_val >> 16) & 0xFF;
    cfr[1] = (cfr_val >> 8)  & 0xFF;
    cfr[2] =  cfr_val        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_CFR, cfr, 3);

    /* 2. CFTW: freq_hz / 486.4 MHz × 2^32 */
    uint64_t ftw = ((uint64_t)freq_hz << 32) / AD9959_SYSCLK_HZ;
    uint8_t ftw_buf[4];
    ftw_buf[0] = (ftw >> 24) & 0xFF;
    ftw_buf[1] = (ftw >> 16) & 0xFF;
    ftw_buf[2] = (ftw >> 8)  & 0xFF;
    ftw_buf[3] =  ftw        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_CFTW, ftw_buf, 4);

    /* 3. ACR: max amplitude (ASF=0x3FF), amp multiplier enabled */
    uint8_t acr[3];
    uint32_t acr_val = ((uint32_t)(0x3FF & ACR_ASF_Msk) << ACR_ASF_Pos)
                     | ACR_AMP_MULT_ENABLE;
    acr[0] = (acr_val >> 16) & 0xFF;
    acr[1] = (acr_val >> 8)  & 0xFF;
    acr[2] =  acr_val        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_ACR, acr, 3);

    /* 4. IO_UPDATE: latch all registers */
    AD9959_IOUpdate();
}
