/**
 ******************************************************************************
 * @file    ad9959.c
 * @brief   AD9959 DDS Driver Implementation
 *
 * 2-wire serial mode:
 *   SDIO0 = SPI1_MOSI (PD7), SDIO1 = SPI3_MOSI (PD6)
 *   SCLK  = SPI1_SCK (PB3) + SPI3_SCK (PC10) synchronous
 *   CS    = SPI1_NSS (PA15) hardware pulse mode
 *
 * Phase 1: both SPI lanes send identical data (redundant dual-wire).
 * Encoder pre-splits data if bit-interleaving is needed later.
 ******************************************************************************
 */

#include "ad9959.h"
#include "ad9959_reg.h"
#include "bsp_spi.h"
#include "bsp_gpio.h"
#include "bsp_tim.h"
#include "drv_74hc595_1.h"
#include <string.h>

/* ================================================================
 * Internal: Power-Up Sequence (via 595)
 * ================================================================ */

static void AD9959_PowerUpSequence(void)
{
    /* Full DDS power-up via 74HC595:
     *   DRV_595_PowerSeq_Init() handles:
     *     1. OE disabled, all outputs low
     *     2. Enable DDS 1.8V digital (DDSPWREN1V8D)
     *     3. Enable DDS 1.8V analog  (DDSPWREN1V8A)
     *     4. Wait 10ms for rails
     *     5. Enable DDS 3.3V digital (DDSPWREN_3V3D)
     *     6. Set REF_CLK mode = 3.3V (DDSCLKMODE33)
     *     7. Master Reset pulse (DDSMASTERRST)
     *     8. Enable outputs
     */
    DRV_595_PowerSeq_Init();
}

/* ================================================================
 * Internal: PLL Configuration (FR1)
 * REF_CLK = 50 MHz (TIM15), SYSCLK = 500 MHz
 * PFD = 50/2 = 25 MHz, PLL x20 = 500 MHz
 * ================================================================ */

static void AD9959_ConfigPLL(void)
{
    /* Start 50 MHz REF_CLK from TIM15 first */
    BSP_TIM15_SetREFCLK(50000000UL);
    BSP_TIM15_Start();

    uint8_t fr1_data[3];
    uint32_t fr1_val = 0;

    /* VCO gain = HIGH (SYSCLK > 255 MHz)  [23] */
    fr1_val |= FR1_VCO_GAIN_HIGH;
    /* PLL divider = 20  [22:18] */
    fr1_val |= FR1_PLL_DIV(20);
    /* Charge pump = 150 uA  [17:16] */
    fr1_val |= FR1_CP_150uA;

    fr1_data[0] = (fr1_val >> 16) & 0xFF;
    fr1_data[1] = (fr1_val >> 8)  & 0xFF;
    fr1_data[2] =  fr1_val        & 0xFF;

    AD9959_WriteRegister(AD9959_REG_FR1, fr1_data, 3);
}

/* ================================================================
 * Public API
 * ================================================================ */

void AD9959_Init(void)
{
    AD9959_PowerUpSequence();
    AD9959_ConfigPLL();

    /* Enable all 4 channels, 2-bit serial (SDIO0+SDIO1), MSB first */
    uint8_t csr = CSR_CH0_ENABLE | CSR_CH1_ENABLE |
                  CSR_CH2_ENABLE | CSR_CH3_ENABLE;
    csr |= CSR_IO_MODE_2BIT;
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    AD9959_IOUpdate();
}

void AD9959_IOUpdate(void)
{
    /* Init-phase software IO_UPDATE: briefly reconfigure PC6 as GPIO,
     * pulse high, restore to AF (TIM8_CH1).
     * Runtime IO_UPDATE is generated by TIM8 CH1 hardware pulse. */
    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = SYNC_9959_IO_UPDATE_Pin;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    HAL_GPIO_Init(SYNC_9959_IO_UPDATE_GPIO_Port, &gpio);

    HAL_GPIO_WritePin(SYNC_9959_IO_UPDATE_GPIO_Port, SYNC_9959_IO_UPDATE_Pin, GPIO_PIN_SET);
    for (volatile int i = 0; i < 100; i++) {}
    HAL_GPIO_WritePin(SYNC_9959_IO_UPDATE_GPIO_Port, SYNC_9959_IO_UPDATE_Pin, GPIO_PIN_RESET);

    /* Restore AF for TIM8_CH1 */
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Alternate = GPIO_AF3_TIM8;
    HAL_GPIO_Init(SYNC_9959_IO_UPDATE_GPIO_Port, &gpio);
}

void AD9959_Reset(void)
{
    /* DDS Master Reset via 595 (DDSMASTERRST bit, active low) */
    DRV_595_SetBit(SHIFTREG_DDS_MASTERRST, 0);   /* assert reset */
    HAL_Delay(1);
    DRV_595_SetBit(SHIFTREG_DDS_MASTERRST, 1);   /* release reset */
}

void AD9959_PowerDown(bool enable)
{
    /* DDS power-down via 595 (DDSPDN bit) */
    DRV_595_SetBit(SHIFTREG_DDS_PDN, enable ? 1 : 0);
}

/* ================================================================
 * Register Access
 * ================================================================ */

void AD9959_WriteRegister(uint8_t reg, const uint8_t *data, uint8_t num_bytes)
{
    uint8_t frame[32];
    if (num_bytes > 31) return;
    frame[0] = reg & 0x7F;
    memcpy(frame + 1, data, num_bytes);
    uint8_t total = num_bytes + 1;

    /* Blocking dual-SPI transmit (for init phase).
     * Runtime uses DMA-based trigger instead. */
    BSP_SPI_Transmit(SPI1, frame, total);
    BSP_SPI_Transmit(SPI3, frame, total);
}

void AD9959_ReadRegister(uint8_t reg, uint8_t *data, uint8_t num_bytes)
{
    (void)reg;
    memset(data, 0, num_bytes);
}

/* ================================================================
 * High-Level Setters
 * ================================================================ */

void AD9959_SetFTW(uint8_t channel, uint32_t ftw)
{
    /* CSR[7:4] selects target channel before CFTW write */
    uint8_t csr = CSR_CHANNEL(channel);
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    uint8_t buf[4];
    buf[0] = (ftw >> 24) & 0xFF;
    buf[1] = (ftw >> 16) & 0xFF;
    buf[2] = (ftw >> 8)  & 0xFF;
    buf[3] =  ftw        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_CFTW, buf, 4);
}

void AD9959_SetASF(uint8_t channel, uint16_t asf)
{
    /* CSR[7:4] selects channel; ACR has NO internal channel bits */
    uint8_t csr = CSR_CHANNEL(channel);
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    uint8_t buf[3];
    uint32_t acr = ((uint32_t)(asf & ACR_ASF_Msk) << ACR_ASF_Pos) |
                   ACR_AMP_MULT_ENABLE;
    buf[0] = (acr >> 16) & 0xFF;
    buf[1] = (acr >> 8)  & 0xFF;
    buf[2] =  acr        & 0xFF;
    AD9959_WriteRegister(AD9959_REG_ACR, buf, 3);
}

void AD9959_SetPOW(uint8_t channel, uint16_t pow)
{
    uint8_t csr = CSR_CHANNEL(channel);
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);

    uint8_t buf[2];
    buf[0] = (pow >> 8) & 0xFF;
    buf[1] =  pow       & 0xFF;
    AD9959_WriteRegister(AD9959_REG_CPOW, buf, 2);
}

void AD9959_SetChannelMask(uint8_t channel_mask)
{
    /* channel_mask uses CSR[7:4]. Also set 2-wire mode [2:1]=00, MSB first [0]=0. */
    uint8_t csr = (channel_mask << 4) & CSR_CHANNEL_MASK;
    csr |= CSR_IO_MODE_2BIT;
    AD9959_WriteRegister(AD9959_REG_CSR, &csr, 1);
}
